steps:

# build and push the container image
- name: azul/zulu-openjdk:21-latest
  args: [ './gradlew', 'jib', '--image=${_CONTAINER_IMAGE}:$SHORT_SHA', '--no-configuration-cache' ]

# deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args: [
    'run', 'deploy', '${_SERVICE_NAME}',
    '--image', '${_CONTAINER_IMAGE}:$SHORT_SHA',
    '--region', '$LOCATION',
    '--cpu', '${_CPU}',
    '--memory', '${_MEMORY}',
    '--timeout', '${_REQUEST_TIMEOUT}',
    '--min-instances', '${_MIN_INSTANCES}',
    '--max-instances', '${_MAX_INSTANCES}',
    '--cpu-boost',
    '--allow-unauthenticated',
  ]
