name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

env:
  TERM: dumb

jobs:
  assemble-and-check:
    name: Build executable jar, run unit tests and static analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - run: ./gradlew assemble check

  deploy:
    name: Build and push container image to Google Artifact Registry, deploy to Cloud Run
    needs: [ assemble-and-check ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      CPU: 4
      MEMORY: 2Gi
      MIN_INSTANCES: 0
      MAX_INSTANCES: 4
      REQUEST_TIMEOUT: 30s

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm-community'
          java-version: '22'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: gradle/actions/setup-gradle@v4

      - name: Build GraalVM native executable
        run: ./gradlew nativeCompile --no-configuration-cache

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Add environment variable for short SHA
        run: echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.GCP_CONTAINER_IMAGE }}:${{ env.SHA_SHORT }},${{ env.GCP_CONTAINER_IMAGE }}:latest

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.GCP_SERVICE_NAME }} \
            --image ${{ env.GCP_CONTAINER_IMAGE }}:${{ env.SHA_SHORT }} \
            --region ${{ env.GCP_REGION }} \
            --cpu ${{ env.CPU }} \
            --memory ${{ env.MEMORY }} \
            --timeout ${{ env.REQUEST_TIMEOUT }} \
            --min-instances ${{ env.MIN_INSTANCES }} \
            --max-instances ${{ env.MAX_INSTANCES }} \
            --platform managed \
            --allow-unauthenticated

      - name: Cleanup old images
        run: |
          # Get all images except the most recent 2
          IMAGES_TO_DELETE=$(gcloud artifacts docker images list ${{ env.GCP_CONTAINER_IMAGE }} \
            --format="get(DIGEST)" \
            --sort-by="~CREATE_TIME" | tail -n +3)
  
          # Delete the older images
          for DIGEST in $IMAGES_TO_DELETE; do
            gcloud artifacts docker images delete ${{ env.GCP_CONTAINER_IMAGE }}@$DIGEST \
              --delete-tags \
              --quiet
          done
